#!/bin/sh

# Wait up to 15 seconds to make sure /opt partition is mounted
modprobe ip_set

ipset -N unblock iphash


while read domain || [ -n "$domain" ]; do
    nslookup $domain | grep -E -o "([0-9]{1,3}[\.]){3}[0-9]{1,3}" | grep -v '127.0.0.1' | while read -r ipdomain ; do
        ipset -A unblock $ipdomain
    done
done < domains.txt


i=0
while [ $i -le 15 ]
do
    if [ -d /opt/tmp ]
    then
        break
    fi
    sleep 1
    i=`expr $i + 1`
done

# Now resolve DNS name for NTP server
ntp_name=$(nvram get ntp_server0)
grep "$ntp_name" /etc/hosts > /dev/null 2>&1 || \
for ip in $(/opt/sbin/dnscrypt-proxy-hostip $ntp_name)
do
    echo $ip $ntp_name >>  /etc/hosts
done

# and restart NTP client to eliminate 4-5 mins delay
killall ntp && sleep 1
service restart_ntpc
