#!/bin/sh

# Wait up to 15 seconds to make sure /opt partition is mounted
modprobe ip_set

ipset -N unblock iphash
ip rule add fwmark 99 table 99
iptables -A PREROUTING -t mangle -m set --set unblock dst,src -j MARK --set-mark 99


i=0
while [ $i -le 15 ]
do
    if [ -d /opt/tmp ]
    then
        break
    fi
    sleep 1
    i=`expr $i + 1`
done

# Now resolve DNS name for NTP server
ntp_name=$(nvram get ntp_server0)
grep "$ntp_name" /etc/hosts > /dev/null 2>&1 || \
for ip in $(/opt/sbin/dnscrypt-proxy-hostip $ntp_name)
do
    echo $ip $ntp_name >>  /etc/hosts
done

# and restart NTP client to eliminate 4-5 mins delay
killall ntp && sleep 1
service restart_ntpc
